---

- name: install packages
  package:
    name: ["openssh-server", "openssh", "mosh"]
    state: present

- name: set ssh configuration
  template: src=templates/ssh_config.j2 dest=/etc/ssh/ssh_config owner=root group=root mode=0644

- name: set sshd configuration
  template: src=templates/sshd_config.j2 dest=/etc/ssh/sshd_config owner=root group=root mode=0600
  notify:
    - sshd restart

- name: add keyboard interactive group
  group: name={{ ssh_keyboard_interactive_group }} system=true state=present
  when: ssh_keyboard_interactive_group is defined and (ssh_keyboard_interactive_group | length > 0)

- name: Ensure that sshd is running
  service: name=sshd state=started enabled=yes
  register: ssh_service
  ignore_errors: True

- name: failed to start sshd
  fail: msg="failed to start sshd"
  when: (ssh_service is failed and (not ssh_role_debug|bool))

- name: create ssh firewall rules
  template: src=templates/1002-ssh.conf.j2 dest=/etc/ferm/ferm.d/1002-ssh.conf owner=root group=root mode=0644

- name: create mosh firewall rules
  template: src=templates/1004-mosh.conf.j2 dest=/etc/ferm/ferm.d/1004-mosh.conf owner=root group=root mode=0644

- name: create lastlog file
  file:
    path: /var/log/lastlog
    mode: 0644
    group: utmp
    state: file
  ignore_errors: True
