---

- name: install packages
  ansible.builtin.package:
    name: ["openssh-server", "openssh", "mosh"]
    state: present

- name: set ssh configuration
  ansible.builtin.template: src=templates/ssh_config.j2 dest=/etc/ssh/ssh_config.d/10-defaults.conf owner=root group=root mode=0644

- name: set sshd configuration
  ansible.builtin.template: src=templates/sshd_config.j2 dest=/etc/ssh/sshd_config.d/10-defaults.conf owner=root group=root mode=0600
  notify:
    - sshd restart

- name: add keyboard interactive group
  ansible.builtin.group: name={{ ssh_keyboard_interactive_group }} system=true state=present
  when: ssh_keyboard_interactive_group is defined and (ssh_keyboard_interactive_group | length > 0)

- name: ensure that sshd is running
  ansible.builtin.service: name=sshd state=started enabled=yes
  when: not ssh_role_debug|bool

- name: create ssh firewall rules
  ansible.builtin.template: src=templates/ferm-ssh.conf.j2 dest=/etc/ferm/ferm.d/1010-ssh.conf owner=root group=root mode=0600

- name: create mosh firewall rules
  ansible.builtin.template: src=templates/ferm-mosh.conf.j2 dest=/etc/ferm/ferm.d/1010-mosh.conf owner=root group=root mode=0600

- name: create lastlog file
  ansible.builtin.file:
    path: /var/log/lastlog
    mode: 0644
    group: utmp
    state: file
  ignore_errors: true
