---
- name: ssh gather service facts before restart
  ansible.builtin.service_facts:
  listen:
    - ssh restart sshd
    - ssh restart ferm

- name: ssh restart active sshd
  ansible.builtin.systemd_service:
    name: sshd.service
    state: restarted
  when: (ansible_facts.services | default({})).get("sshd.service", {}).get("state") == "running"
  listen: ssh restart sshd

- name: ssh restart active ferm
  ansible.builtin.systemd_service:
    name: ferm.service
    state: restarted
  when: (ansible_facts.services | default({})).get("ferm.service", {}).get("state") == "running"
  listen: ssh restart ferm
