---
- name: Converge
  hosts: all
  vars:
    ssh_role_debug: true
  pre_tasks:
    - name: create optional ferm integration directory
      ansible.builtin.file:
        path: /etc/ferm/ferm.d
        state: directory
        mode: "0755"
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
