---
- name: Converge
  hosts: all
  pre_tasks:
    - name: install firewalld for optional integration testing
      ansible.builtin.package:
        name: firewalld
        state: present

    - name: create optional firewalld policy directory
      ansible.builtin.file:
        path: /etc/firewalld/policies
        state: directory
        mode: "0755"
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
